//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach
    {
        public int IDKhach { get; set; }
        public Nullable<int> CongID { get; set; }
        public Nullable<int> LoaiKhachID { get; set; }
        public Nullable<int> NhaThauID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string HoTen { get; set; }
        public string PhuongTien { get; set; }
        public string BienSo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> PHCDNID { get; set; }
    
        public virtual Cong Cong { get; set; }
        public virtual LoaiKhach LoaiKhach { get; set; }
        public virtual NhaThau NhaThau { get; set; }
    }
}
