//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNhaThauEntities : DbContext
    {
        public QLNhaThauEntities()
            : base("name=QLNhaThauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardNhanVien> CardNhanViens { get; set; }
        public virtual DbSet<CauHinhPheDuyet> CauHinhPheDuyets { get; set; }
        public virtual DbSet<Cong> Congs { get; set; }
        public virtual DbSet<GiaHanHD> GiaHanHDs { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KeQuaHoc> KeQuaHocs { get; set; }
        public virtual DbSet<LoaiH> LoaiHS { get; set; }
        public virtual DbSet<LoaiKhach> LoaiKhaches { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhanVienNT> NhanVienNTs { get; set; }
        public virtual DbSet<NhaThau> NhaThaus { get; set; }
        public virtual DbSet<PCHN_HopDong> PCHN_HopDong { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PheDuyet> PheDuyets { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TongQuan> TongQuans { get; set; }
        public virtual DbSet<VanBan> VanBans { get; set; }
    
        public virtual int Card_Delete(Nullable<int> iDCard)
        {
            var iDCardParameter = iDCard.HasValue ?
                new ObjectParameter("IDCard", iDCard) :
                new ObjectParameter("IDCard", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Card_Delete", iDCardParameter);
        }
    
        public virtual int Card_insert(string maCard, Nullable<System.DateTime> ngayHetHan)
        {
            var maCardParameter = maCard != null ?
                new ObjectParameter("MaCard", maCard) :
                new ObjectParameter("MaCard", typeof(string));
    
            var ngayHetHanParameter = ngayHetHan.HasValue ?
                new ObjectParameter("NgayHetHan", ngayHetHan) :
                new ObjectParameter("NgayHetHan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Card_insert", maCardParameter, ngayHetHanParameter);
        }
    
        public virtual ObjectResult<Card_SearchByID_Result> Card_SearchByID(Nullable<int> iDCard)
        {
            var iDCardParameter = iDCard.HasValue ?
                new ObjectParameter("IDCard", iDCard) :
                new ObjectParameter("IDCard", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Card_SearchByID_Result>("Card_SearchByID", iDCardParameter);
        }
    
        public virtual ObjectResult<Card_select_Result> Card_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Card_select_Result>("Card_select");
        }
    
        public virtual int Card_update(Nullable<int> iDCard, string maCard, Nullable<System.DateTime> ngayHetHan)
        {
            var iDCardParameter = iDCard.HasValue ?
                new ObjectParameter("IDCard", iDCard) :
                new ObjectParameter("IDCard", typeof(int));
    
            var maCardParameter = maCard != null ?
                new ObjectParameter("MaCard", maCard) :
                new ObjectParameter("MaCard", typeof(string));
    
            var ngayHetHanParameter = ngayHetHan.HasValue ?
                new ObjectParameter("NgayHetHan", ngayHetHan) :
                new ObjectParameter("NgayHetHan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Card_update", iDCardParameter, maCardParameter, ngayHetHanParameter);
        }
    
        public virtual int Cong_delete(Nullable<int> iDCong)
        {
            var iDCongParameter = iDCong.HasValue ?
                new ObjectParameter("IDCong", iDCong) :
                new ObjectParameter("IDCong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cong_delete", iDCongParameter);
        }
    
        public virtual int Cong_insert(string tenCong)
        {
            var tenCongParameter = tenCong != null ?
                new ObjectParameter("TenCong", tenCong) :
                new ObjectParameter("TenCong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cong_insert", tenCongParameter);
        }
    
        public virtual ObjectResult<Cong_SearchByID_Result> Cong_SearchByID(Nullable<int> iDCong)
        {
            var iDCongParameter = iDCong.HasValue ?
                new ObjectParameter("IDCong", iDCong) :
                new ObjectParameter("IDCong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cong_SearchByID_Result>("Cong_SearchByID", iDCongParameter);
        }
    
        public virtual ObjectResult<Cong_Select_Result> Cong_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cong_Select_Result>("Cong_Select");
        }
    
        public virtual int Cong_update(Nullable<int> iDCong, string tenCong)
        {
            var iDCongParameter = iDCong.HasValue ?
                new ObjectParameter("IDCong", iDCong) :
                new ObjectParameter("IDCong", typeof(int));
    
            var tenCongParameter = tenCong != null ?
                new ObjectParameter("TenCong", tenCong) :
                new ObjectParameter("TenCong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cong_update", iDCongParameter, tenCongParameter);
        }
    
        public virtual int Delete_PhanQyen(Nullable<int> nguoiDungID)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_PhanQyen", nguoiDungIDParameter);
        }
    
        public virtual int EmplIndentityCard_Delete(Nullable<int> iD, Nullable<int> a)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmplIndentityCard_Delete", iDParameter, aParameter);
        }
    
        public virtual int EmplIndentityCard_insert(Nullable<int> cardId, Nullable<int> nhanVienNTID)
        {
            var cardIdParameter = cardId.HasValue ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(int));
    
            var nhanVienNTIDParameter = nhanVienNTID.HasValue ?
                new ObjectParameter("NhanVienNTID", nhanVienNTID) :
                new ObjectParameter("NhanVienNTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmplIndentityCard_insert", cardIdParameter, nhanVienNTIDParameter);
        }
    
        public virtual ObjectResult<EmplIndentityCard_SearchByID_Result> EmplIndentityCard_SearchByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmplIndentityCard_SearchByID_Result>("EmplIndentityCard_SearchByID", iDParameter);
        }
    
        public virtual ObjectResult<EmplIndentityCard_select_Result> EmplIndentityCard_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmplIndentityCard_select_Result>("EmplIndentityCard_select");
        }
    
        public virtual int EmplIndentityCard_update(Nullable<int> iD, Nullable<int> cardId, Nullable<int> nhanVienNTID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var cardIdParameter = cardId.HasValue ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(int));
    
            var nhanVienNTIDParameter = nhanVienNTID.HasValue ?
                new ObjectParameter("NhanVienNTID", nhanVienNTID) :
                new ObjectParameter("NhanVienNTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmplIndentityCard_update", iDParameter, cardIdParameter, nhanVienNTIDParameter);
        }
    
        public virtual int GiaHanHopDong_Delete(Nullable<int> iDGHHD)
        {
            var iDGHHDParameter = iDGHHD.HasValue ?
                new ObjectParameter("IDGHHD", iDGHHD) :
                new ObjectParameter("IDGHHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaHanHopDong_Delete", iDGHHDParameter);
        }
    
        public virtual int GiaHanHopDong_Insert(Nullable<int> hDID, string lyDo, Nullable<System.DateTime> ngayKetThuc)
        {
            var hDIDParameter = hDID.HasValue ?
                new ObjectParameter("HDID", hDID) :
                new ObjectParameter("HDID", typeof(int));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaHanHopDong_Insert", hDIDParameter, lyDoParameter, ngayKetThucParameter);
        }
    
        public virtual ObjectResult<GiaHanHopDong_SearchByID_Result> GiaHanHopDong_SearchByID(Nullable<int> iDGHHD)
        {
            var iDGHHDParameter = iDGHHD.HasValue ?
                new ObjectParameter("IDGHHD", iDGHHD) :
                new ObjectParameter("IDGHHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaHanHopDong_SearchByID_Result>("GiaHanHopDong_SearchByID", iDGHHDParameter);
        }
    
        public virtual ObjectResult<GiaHanHopDong_select_Result> GiaHanHopDong_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaHanHopDong_select_Result>("GiaHanHopDong_select");
        }
    
        public virtual int GiaHanHopDong_update(Nullable<int> iDGHHD, Nullable<int> hDID, string lyDo, Nullable<System.DateTime> ngayKetThuc)
        {
            var iDGHHDParameter = iDGHHD.HasValue ?
                new ObjectParameter("IDGHHD", iDGHHD) :
                new ObjectParameter("IDGHHD", typeof(int));
    
            var hDIDParameter = hDID.HasValue ?
                new ObjectParameter("HDID", hDID) :
                new ObjectParameter("HDID", typeof(int));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaHanHopDong_update", iDGHHDParameter, hDIDParameter, lyDoParameter, ngayKetThucParameter);
        }
    
        public virtual int HopDong_delete(Nullable<int> iDHD)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HopDong_delete", iDHDParameter);
        }
    
        public virtual int HopDong_insert(string soHD, string tenHD, string nguoiDaiDien, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, string ghiChu, string file, Nullable<int> nhaThauID, Nullable<int> phongBanID, ObjectParameter iDHD, Nullable<int> pCNID)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            var tenHDParameter = tenHD != null ?
                new ObjectParameter("TenHD", tenHD) :
                new ObjectParameter("TenHD", typeof(string));
    
            var nguoiDaiDienParameter = nguoiDaiDien != null ?
                new ObjectParameter("NguoiDaiDien", nguoiDaiDien) :
                new ObjectParameter("NguoiDaiDien", typeof(string));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var fileParameter = file != null ?
                new ObjectParameter("File", file) :
                new ObjectParameter("File", typeof(string));
    
            var nhaThauIDParameter = nhaThauID.HasValue ?
                new ObjectParameter("NhaThauID", nhaThauID) :
                new ObjectParameter("NhaThauID", typeof(int));
    
            var phongBanIDParameter = phongBanID.HasValue ?
                new ObjectParameter("PhongBanID", phongBanID) :
                new ObjectParameter("PhongBanID", typeof(int));
    
            var pCNIDParameter = pCNID.HasValue ?
                new ObjectParameter("PCNID", pCNID) :
                new ObjectParameter("PCNID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HopDong_insert", soHDParameter, tenHDParameter, nguoiDaiDienParameter, ngayBDParameter, ngayKTParameter, ghiChuParameter, fileParameter, nhaThauIDParameter, phongBanIDParameter, iDHD, pCNIDParameter);
        }
    
        public virtual ObjectResult<HopDong_SearchByID_Result> HopDong_SearchByID(Nullable<int> iDHD)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HopDong_SearchByID_Result>("HopDong_SearchByID", iDHDParameter);
        }
    
        public virtual ObjectResult<HopDong_select_Result> HopDong_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HopDong_select_Result>("HopDong_select");
        }
    
        public virtual int HopDong_update(Nullable<int> iDHD, string soHD, string tenHD, string nguoiDaiDien, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, string ghiChu, string file, Nullable<int> nhaThauID, Nullable<int> phongBanID)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            var tenHDParameter = tenHD != null ?
                new ObjectParameter("TenHD", tenHD) :
                new ObjectParameter("TenHD", typeof(string));
    
            var nguoiDaiDienParameter = nguoiDaiDien != null ?
                new ObjectParameter("NguoiDaiDien", nguoiDaiDien) :
                new ObjectParameter("NguoiDaiDien", typeof(string));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var fileParameter = file != null ?
                new ObjectParameter("File", file) :
                new ObjectParameter("File", typeof(string));
    
            var nhaThauIDParameter = nhaThauID.HasValue ?
                new ObjectParameter("NhaThauID", nhaThauID) :
                new ObjectParameter("NhaThauID", typeof(int));
    
            var phongBanIDParameter = phongBanID.HasValue ?
                new ObjectParameter("PhongBanID", phongBanID) :
                new ObjectParameter("PhongBanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HopDong_update", iDHDParameter, soHDParameter, tenHDParameter, nguoiDaiDienParameter, ngayBDParameter, ngayKTParameter, ghiChuParameter, fileParameter, nhaThauIDParameter, phongBanIDParameter);
        }
    
        public virtual ObjectResult<IDKetQuaHoc_ByMaNV_Result> IDKetQuaHoc_ByMaNV(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDKetQuaHoc_ByMaNV_Result>("IDKetQuaHoc_ByMaNV", maNVParameter);
        }
    
        public virtual int KetQuaHoc_Delete(Nullable<int> iDKQHAT)
        {
            var iDKQHATParameter = iDKQHAT.HasValue ?
                new ObjectParameter("IDKQHAT", iDKQHAT) :
                new ObjectParameter("IDKQHAT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQuaHoc_Delete", iDKQHATParameter);
        }
    
        public virtual int KetQuaHoc_insert(Nullable<int> hDID, Nullable<int> nhanVienNTID, Nullable<int> nhaThauID, Nullable<bool> ketQua)
        {
            var hDIDParameter = hDID.HasValue ?
                new ObjectParameter("HDID", hDID) :
                new ObjectParameter("HDID", typeof(int));
    
            var nhanVienNTIDParameter = nhanVienNTID.HasValue ?
                new ObjectParameter("NhanVienNTID", nhanVienNTID) :
                new ObjectParameter("NhanVienNTID", typeof(int));
    
            var nhaThauIDParameter = nhaThauID.HasValue ?
                new ObjectParameter("NhaThauID", nhaThauID) :
                new ObjectParameter("NhaThauID", typeof(int));
    
            var ketQuaParameter = ketQua.HasValue ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQuaHoc_insert", hDIDParameter, nhanVienNTIDParameter, nhaThauIDParameter, ketQuaParameter);
        }
    
        public virtual int KetQuaHoc_save(Nullable<int> iDKQHAT, Nullable<bool> ketQua)
        {
            var iDKQHATParameter = iDKQHAT.HasValue ?
                new ObjectParameter("IDKQHAT", iDKQHAT) :
                new ObjectParameter("IDKQHAT", typeof(int));
    
            var ketQuaParameter = ketQua.HasValue ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQuaHoc_save", iDKQHATParameter, ketQuaParameter);
        }
    
        public virtual ObjectResult<KetQuaHoc_SearchByID_Result> KetQuaHoc_SearchByID(Nullable<int> iDKQHAT)
        {
            var iDKQHATParameter = iDKQHAT.HasValue ?
                new ObjectParameter("IDKQHAT", iDKQHAT) :
                new ObjectParameter("IDKQHAT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KetQuaHoc_SearchByID_Result>("KetQuaHoc_SearchByID", iDKQHATParameter);
        }
    
        public virtual ObjectResult<KetQuaHoc_select_Result> KetQuaHoc_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KetQuaHoc_select_Result>("KetQuaHoc_select");
        }
    
        public virtual int KetQuaHoc_update(Nullable<int> iDKQHAT, Nullable<int> nhanVienNTID, Nullable<int> hDID, Nullable<int> nhaThauID, Nullable<System.DateTime> ngayHoc, Nullable<bool> ketQua)
        {
            var iDKQHATParameter = iDKQHAT.HasValue ?
                new ObjectParameter("IDKQHAT", iDKQHAT) :
                new ObjectParameter("IDKQHAT", typeof(int));
    
            var nhanVienNTIDParameter = nhanVienNTID.HasValue ?
                new ObjectParameter("NhanVienNTID", nhanVienNTID) :
                new ObjectParameter("NhanVienNTID", typeof(int));
    
            var hDIDParameter = hDID.HasValue ?
                new ObjectParameter("HDID", hDID) :
                new ObjectParameter("HDID", typeof(int));
    
            var nhaThauIDParameter = nhaThauID.HasValue ?
                new ObjectParameter("NhaThauID", nhaThauID) :
                new ObjectParameter("NhaThauID", typeof(int));
    
            var ngayHocParameter = ngayHoc.HasValue ?
                new ObjectParameter("NgayHoc", ngayHoc) :
                new ObjectParameter("NgayHoc", typeof(System.DateTime));
    
            var ketQuaParameter = ketQua.HasValue ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQuaHoc_update", iDKQHATParameter, nhanVienNTIDParameter, hDIDParameter, nhaThauIDParameter, ngayHocParameter, ketQuaParameter);
        }
    
        public virtual int LoaiKhach_delete(Nullable<int> iDLoaiKhach)
        {
            var iDLoaiKhachParameter = iDLoaiKhach.HasValue ?
                new ObjectParameter("IDLoaiKhach", iDLoaiKhach) :
                new ObjectParameter("IDLoaiKhach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiKhach_delete", iDLoaiKhachParameter);
        }
    
        public virtual int LoaiKhach_insert(Nullable<int> iDLoaiKhach, string tenKhach)
        {
            var iDLoaiKhachParameter = iDLoaiKhach.HasValue ?
                new ObjectParameter("IDLoaiKhach", iDLoaiKhach) :
                new ObjectParameter("IDLoaiKhach", typeof(int));
    
            var tenKhachParameter = tenKhach != null ?
                new ObjectParameter("TenKhach", tenKhach) :
                new ObjectParameter("TenKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiKhach_insert", iDLoaiKhachParameter, tenKhachParameter);
        }
    
        public virtual ObjectResult<LoaiKhach_SearchByID_Result> LoaiKhach_SearchByID(Nullable<int> iDLoaiKhach)
        {
            var iDLoaiKhachParameter = iDLoaiKhach.HasValue ?
                new ObjectParameter("IDLoaiKhach", iDLoaiKhach) :
                new ObjectParameter("IDLoaiKhach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiKhach_SearchByID_Result>("LoaiKhach_SearchByID", iDLoaiKhachParameter);
        }
    
        public virtual ObjectResult<LoaiKhach_Select_Result> LoaiKhach_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiKhach_Select_Result>("LoaiKhach_Select");
        }
    
        public virtual int LoaiKhach_update(Nullable<int> iDLoaiKhach, string tenKhach)
        {
            var iDLoaiKhachParameter = iDLoaiKhach.HasValue ?
                new ObjectParameter("IDLoaiKhach", iDLoaiKhach) :
                new ObjectParameter("IDLoaiKhach", typeof(int));
    
            var tenKhachParameter = tenKhach != null ?
                new ObjectParameter("TenKhach", tenKhach) :
                new ObjectParameter("TenKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiKhach_update", iDLoaiKhachParameter, tenKhachParameter);
        }
    
        public virtual ObjectResult<string> MaNVNT_KQHocANT(Nullable<int> nhanVienNTID)
        {
            var nhanVienNTIDParameter = nhanVienNTID.HasValue ?
                new ObjectParameter("NhanVienNTID", nhanVienNTID) :
                new ObjectParameter("NhanVienNTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MaNVNT_KQHocANT", nhanVienNTIDParameter);
        }
    
        public virtual int NguoiDung_CapNhatQuyen(Nullable<int> iDNguoiDung, string danhSachQuyen)
        {
            var iDNguoiDungParameter = iDNguoiDung.HasValue ?
                new ObjectParameter("IDNguoiDung", iDNguoiDung) :
                new ObjectParameter("IDNguoiDung", typeof(int));
    
            var danhSachQuyenParameter = danhSachQuyen != null ?
                new ObjectParameter("DanhSachQuyen", danhSachQuyen) :
                new ObjectParameter("DanhSachQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NguoiDung_CapNhatQuyen", iDNguoiDungParameter, danhSachQuyenParameter);
        }
    
        public virtual ObjectResult<NguoiDung_danhsach_Result> NguoiDung_danhsach(Nullable<int> iDPhanQuyen, Nullable<int> iDNhanVien)
        {
            var iDPhanQuyenParameter = iDPhanQuyen.HasValue ?
                new ObjectParameter("IDPhanQuyen", iDPhanQuyen) :
                new ObjectParameter("IDPhanQuyen", typeof(int));
    
            var iDNhanVienParameter = iDNhanVien.HasValue ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoiDung_danhsach_Result>("NguoiDung_danhsach", iDPhanQuyenParameter, iDNhanVienParameter);
        }
    
        public virtual int NguoiDung_delete(Nullable<int> iDNguoiDung)
        {
            var iDNguoiDungParameter = iDNguoiDung.HasValue ?
                new ObjectParameter("IDNguoiDung", iDNguoiDung) :
                new ObjectParameter("IDNguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NguoiDung_delete", iDNguoiDungParameter);
        }
    
        public virtual int NguoiDung_DeletePermission(string tenDangNhap, ObjectParameter iDNguoiDung)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NguoiDung_DeletePermission", tenDangNhapParameter, iDNguoiDung);
        }
    
        public virtual ObjectResult<NguoiDung_get_IDPhanQuyen_Result> NguoiDung_get_IDPhanQuyen(Nullable<int> nguoiDungID)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoiDung_get_IDPhanQuyen_Result>("NguoiDung_get_IDPhanQuyen", nguoiDungIDParameter);
        }
    
        public virtual ObjectResult<NguoiDung_Get_PhanQuyen_Result> NguoiDung_Get_PhanQuyen(Nullable<int> nguoiDungID)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoiDung_Get_PhanQuyen_Result>("NguoiDung_Get_PhanQuyen", nguoiDungIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> NguoiDung_GetAllId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NguoiDung_GetAllId");
        }
    
        public virtual int NguoiDung_insert(string tenDangNhap, string matKhau, string email, Nullable<int> phongBanID, Nullable<int> nhanVienID, ObjectParameter idNguoiDung)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phongBanIDParameter = phongBanID.HasValue ?
                new ObjectParameter("PhongBanID", phongBanID) :
                new ObjectParameter("PhongBanID", typeof(int));
    
            var nhanVienIDParameter = nhanVienID.HasValue ?
                new ObjectParameter("NhanVienID", nhanVienID) :
                new ObjectParameter("NhanVienID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NguoiDung_insert", tenDangNhapParameter, matKhauParameter, emailParameter, phongBanIDParameter, nhanVienIDParameter, idNguoiDung);
        }
    
        public virtual ObjectResult<Nullable<int>> NguoiDung_Max_ID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NguoiDung_Max_ID");
        }
    
        public virtual ObjectResult<NguoiDung_SearchByID_Result> NguoiDung_SearchByID(Nullable<int> iDNguoiDung)
        {
            var iDNguoiDungParameter = iDNguoiDung.HasValue ?
                new ObjectParameter("IDNguoiDung", iDNguoiDung) :
                new ObjectParameter("IDNguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoiDung_SearchByID_Result>("NguoiDung_SearchByID", iDNguoiDungParameter);
        }
    
        public virtual ObjectResult<NguoiDung_select_Result> NguoiDung_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoiDung_select_Result>("NguoiDung_select");
        }
    
        public virtual int NguoiDung_update(Nullable<int> iDNguoiDung, string tenDangNhap, string matKhau, string email, Nullable<int> phongBanID, Nullable<int> nhanVienID)
        {
            var iDNguoiDungParameter = iDNguoiDung.HasValue ?
                new ObjectParameter("IDNguoiDung", iDNguoiDung) :
                new ObjectParameter("IDNguoiDung", typeof(int));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phongBanIDParameter = phongBanID.HasValue ?
                new ObjectParameter("PhongBanID", phongBanID) :
                new ObjectParameter("PhongBanID", typeof(int));
    
            var nhanVienIDParameter = nhanVienID.HasValue ?
                new ObjectParameter("NhanVienID", nhanVienID) :
                new ObjectParameter("NhanVienID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NguoiDung_update", iDNguoiDungParameter, tenDangNhapParameter, matKhauParameter, emailParameter, phongBanIDParameter, nhanVienIDParameter);
        }
    
        public virtual int NguoiDung_update_Quyen(Nullable<int> nguoiDungID, Nullable<int> quyenID)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            var quyenIDParameter = quyenID.HasValue ?
                new ObjectParameter("QuyenID", quyenID) :
                new ObjectParameter("QuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NguoiDung_update_Quyen", nguoiDungIDParameter, quyenIDParameter);
        }
    
        public virtual int NhanVien_delete(Nullable<int> iDNhanVien)
        {
            var iDNhanVienParameter = iDNhanVien.HasValue ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_delete", iDNhanVienParameter);
        }
    
        public virtual int NhanVien_insert(Nullable<int> iDNhanVien, string maNV, string tenNV, string tenNVKD, string diaChi, string sDT, string email, Nullable<System.DateTime> ngayVaolam, Nullable<bool> tinhTrangLV, Nullable<System.DateTime> ngayNghiViec, Nullable<System.DateTime> createDate, Nullable<System.DateTime> updateDate, string createBy, string updateBy)
        {
            var iDNhanVienParameter = iDNhanVien.HasValue ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(int));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var tenNVKDParameter = tenNVKD != null ?
                new ObjectParameter("TenNVKD", tenNVKD) :
                new ObjectParameter("TenNVKD", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var ngayVaolamParameter = ngayVaolam.HasValue ?
                new ObjectParameter("NgayVaolam", ngayVaolam) :
                new ObjectParameter("NgayVaolam", typeof(System.DateTime));
    
            var tinhTrangLVParameter = tinhTrangLV.HasValue ?
                new ObjectParameter("TinhTrangLV", tinhTrangLV) :
                new ObjectParameter("TinhTrangLV", typeof(bool));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var createByParameter = createBy != null ?
                new ObjectParameter("CreateBy", createBy) :
                new ObjectParameter("CreateBy", typeof(string));
    
            var updateByParameter = updateBy != null ?
                new ObjectParameter("UpdateBy", updateBy) :
                new ObjectParameter("UpdateBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_insert", iDNhanVienParameter, maNVParameter, tenNVParameter, tenNVKDParameter, diaChiParameter, sDTParameter, emailParameter, ngayVaolamParameter, tinhTrangLVParameter, ngayNghiViecParameter, createDateParameter, updateDateParameter, createByParameter, updateByParameter);
        }
    
        public virtual ObjectResult<NhanVien_SearchByID_Result> NhanVien_SearchByID(Nullable<int> iDNhanVien)
        {
            var iDNhanVienParameter = iDNhanVien.HasValue ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_SearchByID_Result>("NhanVien_SearchByID", iDNhanVienParameter);
        }
    
        public virtual ObjectResult<NhanVien_select_Result> NhanVien_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_select_Result>("NhanVien_select");
        }
    
        public virtual int NhanVien_update(Nullable<int> iDNhanVien, string maNV, string tenNV, string tenNVKD, string diaChi, string sDT, string email, Nullable<System.DateTime> ngayVaolam, Nullable<bool> tinhTrangLV, Nullable<System.DateTime> ngayNghiViec)
        {
            var iDNhanVienParameter = iDNhanVien.HasValue ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(int));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var tenNVKDParameter = tenNVKD != null ?
                new ObjectParameter("TenNVKD", tenNVKD) :
                new ObjectParameter("TenNVKD", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var ngayVaolamParameter = ngayVaolam.HasValue ?
                new ObjectParameter("NgayVaolam", ngayVaolam) :
                new ObjectParameter("NgayVaolam", typeof(System.DateTime));
    
            var tinhTrangLVParameter = tinhTrangLV.HasValue ?
                new ObjectParameter("TinhTrangLV", tinhTrangLV) :
                new ObjectParameter("TinhTrangLV", typeof(bool));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_update", iDNhanVienParameter, maNVParameter, tenNVParameter, tenNVKDParameter, diaChiParameter, sDTParameter, emailParameter, ngayVaolamParameter, tinhTrangLVParameter, ngayNghiViecParameter);
        }
    
        public virtual int NhanVienNT_Delete(Nullable<int> iDNVNT)
        {
            var iDNVNTParameter = iDNVNT.HasValue ?
                new ObjectParameter("IDNVNT", iDNVNT) :
                new ObjectParameter("IDNVNT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVienNT_Delete", iDNVNTParameter);
        }
    
        public virtual int NhanVienNT_insert(string maNV, string sCMND, string hoTen, string chucVu, Nullable<System.DateTime> ngaySinh, Nullable<int> gioiTinh, string quocTich, ObjectParameter iDNVNT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var sCMNDParameter = sCMND != null ?
                new ObjectParameter("SCMND", sCMND) :
                new ObjectParameter("SCMND", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVienNT_insert", maNVParameter, sCMNDParameter, hoTenParameter, chucVuParameter, ngaySinhParameter, gioiTinhParameter, quocTichParameter, iDNVNT);
        }
    
        public virtual ObjectResult<NhanVienNT_SearchByID_Result> NhanVienNT_SearchByID(Nullable<int> iDNVNT)
        {
            var iDNVNTParameter = iDNVNT.HasValue ?
                new ObjectParameter("IDNVNT", iDNVNT) :
                new ObjectParameter("IDNVNT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVienNT_SearchByID_Result>("NhanVienNT_SearchByID", iDNVNTParameter);
        }
    
        public virtual ObjectResult<NhanVienNT_select_Result> NhanVienNT_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVienNT_select_Result>("NhanVienNT_select");
        }
    
        public virtual int NhanVienNT_update(Nullable<int> iDNVNT, string maNV, string sCMND, string hoTen, string chucVu, Nullable<System.DateTime> ngaySinh, Nullable<int> gioiTinh, string quocTich)
        {
            var iDNVNTParameter = iDNVNT.HasValue ?
                new ObjectParameter("IDNVNT", iDNVNT) :
                new ObjectParameter("IDNVNT", typeof(int));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var sCMNDParameter = sCMND != null ?
                new ObjectParameter("SCMND", sCMND) :
                new ObjectParameter("SCMND", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVienNT_update", iDNVNTParameter, maNVParameter, sCMNDParameter, hoTenParameter, chucVuParameter, ngaySinhParameter, gioiTinhParameter, quocTichParameter);
        }
    
        public virtual int Nhathau_insert(string maNT, string mST, string ten, string diachi, string dienThoai, string email)
        {
            var maNTParameter = maNT != null ?
                new ObjectParameter("MaNT", maNT) :
                new ObjectParameter("MaNT", typeof(string));
    
            var mSTParameter = mST != null ?
                new ObjectParameter("MST", mST) :
                new ObjectParameter("MST", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhathau_insert", maNTParameter, mSTParameter, tenParameter, diachiParameter, dienThoaiParameter, emailParameter);
        }
    
        public virtual ObjectResult<NhaThau_list_Result> NhaThau_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhaThau_list_Result>("NhaThau_list");
        }
    
        public virtual ObjectResult<Nhathau_SearchByID_Result> Nhathau_SearchByID(Nullable<int> iDNhaThau)
        {
            var iDNhaThauParameter = iDNhaThau.HasValue ?
                new ObjectParameter("IDNhaThau", iDNhaThau) :
                new ObjectParameter("IDNhaThau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhathau_SearchByID_Result>("Nhathau_SearchByID", iDNhaThauParameter);
        }
    
        public virtual ObjectResult<NhaThau_select_Result> NhaThau_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhaThau_select_Result>("NhaThau_select");
        }
    
        public virtual int Nhathau_update(Nullable<int> iDNhaThau, string maNT, string mST, string ten, string diachi, string dienThoai, string email)
        {
            var iDNhaThauParameter = iDNhaThau.HasValue ?
                new ObjectParameter("IDNhaThau", iDNhaThau) :
                new ObjectParameter("IDNhaThau", typeof(int));
    
            var maNTParameter = maNT != null ?
                new ObjectParameter("MaNT", maNT) :
                new ObjectParameter("MaNT", typeof(string));
    
            var mSTParameter = mST != null ?
                new ObjectParameter("MST", mST) :
                new ObjectParameter("MST", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhathau_update", iDNhaThauParameter, maNTParameter, mSTParameter, tenParameter, diachiParameter, dienThoaiParameter, emailParameter);
        }
    
        public virtual int PCHN_HopDong_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PCHN_HopDong_Delete", iDParameter);
        }
    
        public virtual int PCHN_HopDong_Insert(Nullable<int> phongBanID, Nullable<int> hopDongID)
        {
            var phongBanIDParameter = phongBanID.HasValue ?
                new ObjectParameter("PhongBanID", phongBanID) :
                new ObjectParameter("PhongBanID", typeof(int));
    
            var hopDongIDParameter = hopDongID.HasValue ?
                new ObjectParameter("HopDongID", hopDongID) :
                new ObjectParameter("HopDongID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PCHN_HopDong_Insert", phongBanIDParameter, hopDongIDParameter);
        }
    
        public virtual ObjectResult<PCHN_HopDong_SearchByID_Result> PCHN_HopDong_SearchByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCHN_HopDong_SearchByID_Result>("PCHN_HopDong_SearchByID", iDParameter);
        }
    
        public virtual ObjectResult<PCHN_HopDong_select_Result> PCHN_HopDong_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCHN_HopDong_select_Result>("PCHN_HopDong_select");
        }
    
        public virtual int PCHN_HopDong_update(Nullable<int> iD, Nullable<int> phongBanID, Nullable<int> hopDongID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var phongBanIDParameter = phongBanID.HasValue ?
                new ObjectParameter("PhongBanID", phongBanID) :
                new ObjectParameter("PhongBanID", typeof(int));
    
            var hopDongIDParameter = hopDongID.HasValue ?
                new ObjectParameter("HopDongID", hopDongID) :
                new ObjectParameter("HopDongID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PCHN_HopDong_update", iDParameter, phongBanIDParameter, hopDongIDParameter);
        }
    
        public virtual int PhanQuyen_delete(Nullable<int> iDPhanQuyen)
        {
            var iDPhanQuyenParameter = iDPhanQuyen.HasValue ?
                new ObjectParameter("IDPhanQuyen", iDPhanQuyen) :
                new ObjectParameter("IDPhanQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhanQuyen_delete", iDPhanQuyenParameter);
        }
    
        public virtual int PhanQuyen_insert(Nullable<int> nguoiDungID, Nullable<int> quyenID)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            var quyenIDParameter = quyenID.HasValue ?
                new ObjectParameter("QuyenID", quyenID) :
                new ObjectParameter("QuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhanQuyen_insert", nguoiDungIDParameter, quyenIDParameter);
        }
    
        public virtual ObjectResult<PhanQuyen_NDSelectAll_Result> PhanQuyen_NDSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanQuyen_NDSelectAll_Result>("PhanQuyen_NDSelectAll");
        }
    
        public virtual ObjectResult<PhanQuyen_select_Result> PhanQuyen_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanQuyen_select_Result>("PhanQuyen_select");
        }
    
        public virtual ObjectResult<PhanQuyen_selectAll_Result> PhanQuyen_selectAll(Nullable<int> nguoiDungID)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanQuyen_selectAll_Result>("PhanQuyen_selectAll", nguoiDungIDParameter);
        }
    
        public virtual int PhanQuyen_update(Nullable<int> iDPhanQuyen, Nullable<int> nguoiDungID, Nullable<int> quyenID)
        {
            var iDPhanQuyenParameter = iDPhanQuyen.HasValue ?
                new ObjectParameter("IDPhanQuyen", iDPhanQuyen) :
                new ObjectParameter("IDPhanQuyen", typeof(int));
    
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            var quyenIDParameter = quyenID.HasValue ?
                new ObjectParameter("QuyenID", quyenID) :
                new ObjectParameter("QuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhanQuyen_update", iDPhanQuyenParameter, nguoiDungIDParameter, quyenIDParameter);
        }
    
        public virtual int PheDuyet_Insert(Nullable<int> nguoiDungID, Nullable<int> loaiHSID, Nullable<bool> tinhTrang, string ghiChu)
        {
            var nguoiDungIDParameter = nguoiDungID.HasValue ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(int));
    
            var loaiHSIDParameter = loaiHSID.HasValue ?
                new ObjectParameter("LoaiHSID", loaiHSID) :
                new ObjectParameter("LoaiHSID", typeof(int));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PheDuyet_Insert", nguoiDungIDParameter, loaiHSIDParameter, tinhTrangParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<PheDuyet_SearchByID_Result> PheDuyet_SearchByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PheDuyet_SearchByID_Result>("PheDuyet_SearchByID", iDParameter);
        }
    
        public virtual int PheDuyet_Updata(Nullable<int> iD, string nguoiDungID, string loaiHSID, Nullable<bool> tinhTrang, string ghiChu)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nguoiDungIDParameter = nguoiDungID != null ?
                new ObjectParameter("NguoiDungID", nguoiDungID) :
                new ObjectParameter("NguoiDungID", typeof(string));
    
            var loaiHSIDParameter = loaiHSID != null ?
                new ObjectParameter("LoaiHSID", loaiHSID) :
                new ObjectParameter("LoaiHSID", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PheDuyet_Updata", iDParameter, nguoiDungIDParameter, loaiHSIDParameter, tinhTrangParameter, ghiChuParameter);
        }
    
        public virtual int PhongBan_delete(Nullable<int> iDPhongBan)
        {
            var iDPhongBanParameter = iDPhongBan.HasValue ?
                new ObjectParameter("IDPhongBan", iDPhongBan) :
                new ObjectParameter("IDPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhongBan_delete", iDPhongBanParameter);
        }
    
        public virtual int PhongBan_insert(string tenVT, string tenDai, Nullable<bool> pCHN)
        {
            var tenVTParameter = tenVT != null ?
                new ObjectParameter("TenVT", tenVT) :
                new ObjectParameter("TenVT", typeof(string));
    
            var tenDaiParameter = tenDai != null ?
                new ObjectParameter("TenDai", tenDai) :
                new ObjectParameter("TenDai", typeof(string));
    
            var pCHNParameter = pCHN.HasValue ?
                new ObjectParameter("PCHN", pCHN) :
                new ObjectParameter("PCHN", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhongBan_insert", tenVTParameter, tenDaiParameter, pCHNParameter);
        }
    
        public virtual ObjectResult<PhongBan_ISPCHN_Result> PhongBan_ISPCHN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan_ISPCHN_Result>("PhongBan_ISPCHN");
        }
    
        public virtual ObjectResult<PhongBan_list_Result> PhongBan_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan_list_Result>("PhongBan_list");
        }
    
        public virtual ObjectResult<Nullable<int>> PhongBan_PCHN_loadedit(Nullable<int> iDHopDong)
        {
            var iDHopDongParameter = iDHopDong.HasValue ?
                new ObjectParameter("IDHopDong", iDHopDong) :
                new ObjectParameter("IDHopDong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PhongBan_PCHN_loadedit", iDHopDongParameter);
        }
    
        public virtual ObjectResult<PhongBan_PCHN_SearchByID_Result> PhongBan_PCHN_SearchByID(Nullable<int> iDHopDong)
        {
            var iDHopDongParameter = iDHopDong.HasValue ?
                new ObjectParameter("IDHopDong", iDHopDong) :
                new ObjectParameter("IDHopDong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan_PCHN_SearchByID_Result>("PhongBan_PCHN_SearchByID", iDHopDongParameter);
        }
    
        public virtual ObjectResult<PhongBan_SearchByID_Result> PhongBan_SearchByID(Nullable<int> iDPhongBan)
        {
            var iDPhongBanParameter = iDPhongBan.HasValue ?
                new ObjectParameter("IDPhongBan", iDPhongBan) :
                new ObjectParameter("IDPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan_SearchByID_Result>("PhongBan_SearchByID", iDPhongBanParameter);
        }
    
        public virtual int PhongBan_update(Nullable<int> iDPhongban, string tenVT, string tenDai, Nullable<bool> pCHN)
        {
            var iDPhongbanParameter = iDPhongban.HasValue ?
                new ObjectParameter("IDPhongban", iDPhongban) :
                new ObjectParameter("IDPhongban", typeof(int));
    
            var tenVTParameter = tenVT != null ?
                new ObjectParameter("TenVT", tenVT) :
                new ObjectParameter("TenVT", typeof(string));
    
            var tenDaiParameter = tenDai != null ?
                new ObjectParameter("TenDai", tenDai) :
                new ObjectParameter("TenDai", typeof(string));
    
            var pCHNParameter = pCHN.HasValue ?
                new ObjectParameter("PCHN", pCHN) :
                new ObjectParameter("PCHN", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhongBan_update", iDPhongbanParameter, tenVTParameter, tenDaiParameter, pCHNParameter);
        }
    
        public virtual int Quyen_delete(Nullable<int> iDQuyen)
        {
            var iDQuyenParameter = iDQuyen.HasValue ?
                new ObjectParameter("IDQuyen", iDQuyen) :
                new ObjectParameter("IDQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Quyen_delete", iDQuyenParameter);
        }
    
        public virtual int Quyen_insert(string tenQuyen)
        {
            var tenQuyenParameter = tenQuyen != null ?
                new ObjectParameter("TenQuyen", tenQuyen) :
                new ObjectParameter("TenQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Quyen_insert", tenQuyenParameter);
        }
    
        public virtual ObjectResult<Quyen_SearchByID_Result> Quyen_SearchByID(Nullable<int> iDQuyen)
        {
            var iDQuyenParameter = iDQuyen.HasValue ?
                new ObjectParameter("IDQuyen", iDQuyen) :
                new ObjectParameter("IDQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Quyen_SearchByID_Result>("Quyen_SearchByID", iDQuyenParameter);
        }
    
        public virtual ObjectResult<Quyen_select_Result> Quyen_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Quyen_select_Result>("Quyen_select");
        }
    
        public virtual int Quyen_update(Nullable<int> iDQuyen, string tenQuyen)
        {
            var iDQuyenParameter = iDQuyen.HasValue ?
                new ObjectParameter("IDQuyen", iDQuyen) :
                new ObjectParameter("IDQuyen", typeof(int));
    
            var tenQuyenParameter = tenQuyen != null ?
                new ObjectParameter("TenQuyen", tenQuyen) :
                new ObjectParameter("TenQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Quyen_update", iDQuyenParameter, tenQuyenParameter);
        }
    
        public virtual ObjectResult<string> SoHD_KQHocANT(Nullable<int> iDHD)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SoHD_KQHocANT", iDHDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<TenNT_HopDong_Result> TenNT_HopDong(Nullable<int> iDNhaThau)
        {
            var iDNhaThauParameter = iDNhaThau.HasValue ?
                new ObjectParameter("IDNhaThau", iDNhaThau) :
                new ObjectParameter("IDNhaThau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TenNT_HopDong_Result>("TenNT_HopDong", iDNhaThauParameter);
        }
    
        public virtual ObjectResult<string> TenNT_KQHocANT(Nullable<int> iDNhaThau)
        {
            var iDNhaThauParameter = iDNhaThau.HasValue ?
                new ObjectParameter("IDNhaThau", iDNhaThau) :
                new ObjectParameter("IDNhaThau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TenNT_KQHocANT", iDNhaThauParameter);
        }
    
        public virtual ObjectResult<TongQuan_Select_Result> TongQuan_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TongQuan_Select_Result>("TongQuan_Select");
        }
    
        public virtual int Nhathau_delete(Nullable<int> iDNhaThau)
        {
            var iDNhaThauParameter = iDNhaThau.HasValue ?
                new ObjectParameter("IDNhaThau", iDNhaThau) :
                new ObjectParameter("IDNhaThau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhathau_delete", iDNhaThauParameter);
        }
    
        public virtual int ViPham_delete(Nullable<int> iDViPham)
        {
            var iDViPhamParameter = iDViPham.HasValue ?
                new ObjectParameter("IDViPham", iDViPham) :
                new ObjectParameter("IDViPham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ViPham_delete", iDViPhamParameter);
        }
    
        public virtual int ViPham_insert(Nullable<int> iDViPham, string maNVVP, string tenNVVP, string tenNhaThau, string hangMuc, string nDViPham, Nullable<System.DateTime> ngayVP, string mucVP, Nullable<int> tongVP, Nullable<bool> catThe)
        {
            var iDViPhamParameter = iDViPham.HasValue ?
                new ObjectParameter("IDViPham", iDViPham) :
                new ObjectParameter("IDViPham", typeof(int));
    
            var maNVVPParameter = maNVVP != null ?
                new ObjectParameter("MaNVVP", maNVVP) :
                new ObjectParameter("MaNVVP", typeof(string));
    
            var tenNVVPParameter = tenNVVP != null ?
                new ObjectParameter("TenNVVP", tenNVVP) :
                new ObjectParameter("TenNVVP", typeof(string));
    
            var tenNhaThauParameter = tenNhaThau != null ?
                new ObjectParameter("TenNhaThau", tenNhaThau) :
                new ObjectParameter("TenNhaThau", typeof(string));
    
            var hangMucParameter = hangMuc != null ?
                new ObjectParameter("HangMuc", hangMuc) :
                new ObjectParameter("HangMuc", typeof(string));
    
            var nDViPhamParameter = nDViPham != null ?
                new ObjectParameter("NDViPham", nDViPham) :
                new ObjectParameter("NDViPham", typeof(string));
    
            var ngayVPParameter = ngayVP.HasValue ?
                new ObjectParameter("NgayVP", ngayVP) :
                new ObjectParameter("NgayVP", typeof(System.DateTime));
    
            var mucVPParameter = mucVP != null ?
                new ObjectParameter("MucVP", mucVP) :
                new ObjectParameter("MucVP", typeof(string));
    
            var tongVPParameter = tongVP.HasValue ?
                new ObjectParameter("TongVP", tongVP) :
                new ObjectParameter("TongVP", typeof(int));
    
            var catTheParameter = catThe.HasValue ?
                new ObjectParameter("CatThe", catThe) :
                new ObjectParameter("CatThe", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ViPham_insert", iDViPhamParameter, maNVVPParameter, tenNVVPParameter, tenNhaThauParameter, hangMucParameter, nDViPhamParameter, ngayVPParameter, mucVPParameter, tongVPParameter, catTheParameter);
        }
    
        public virtual ObjectResult<ViPham_SearchByID_Result> ViPham_SearchByID(Nullable<int> iDViPham)
        {
            var iDViPhamParameter = iDViPham.HasValue ?
                new ObjectParameter("IDViPham", iDViPham) :
                new ObjectParameter("IDViPham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViPham_SearchByID_Result>("ViPham_SearchByID", iDViPhamParameter);
        }
    
        public virtual ObjectResult<ViPham_Select_Result> ViPham_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViPham_Select_Result>("ViPham_Select");
        }
    
        public virtual int ViPham_update(Nullable<int> iDViPham, string maNVVP, string tenNVVP, string tenNhaThau, string hangMuc, string nDViPham, Nullable<System.DateTime> ngayVP, string mucVP, Nullable<int> tongVP, Nullable<bool> catThe)
        {
            var iDViPhamParameter = iDViPham.HasValue ?
                new ObjectParameter("IDViPham", iDViPham) :
                new ObjectParameter("IDViPham", typeof(int));
    
            var maNVVPParameter = maNVVP != null ?
                new ObjectParameter("MaNVVP", maNVVP) :
                new ObjectParameter("MaNVVP", typeof(string));
    
            var tenNVVPParameter = tenNVVP != null ?
                new ObjectParameter("TenNVVP", tenNVVP) :
                new ObjectParameter("TenNVVP", typeof(string));
    
            var tenNhaThauParameter = tenNhaThau != null ?
                new ObjectParameter("TenNhaThau", tenNhaThau) :
                new ObjectParameter("TenNhaThau", typeof(string));
    
            var hangMucParameter = hangMuc != null ?
                new ObjectParameter("HangMuc", hangMuc) :
                new ObjectParameter("HangMuc", typeof(string));
    
            var nDViPhamParameter = nDViPham != null ?
                new ObjectParameter("NDViPham", nDViPham) :
                new ObjectParameter("NDViPham", typeof(string));
    
            var ngayVPParameter = ngayVP.HasValue ?
                new ObjectParameter("NgayVP", ngayVP) :
                new ObjectParameter("NgayVP", typeof(System.DateTime));
    
            var mucVPParameter = mucVP != null ?
                new ObjectParameter("MucVP", mucVP) :
                new ObjectParameter("MucVP", typeof(string));
    
            var tongVPParameter = tongVP.HasValue ?
                new ObjectParameter("TongVP", tongVP) :
                new ObjectParameter("TongVP", typeof(int));
    
            var catTheParameter = catThe.HasValue ?
                new ObjectParameter("CatThe", catThe) :
                new ObjectParameter("CatThe", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ViPham_update", iDViPhamParameter, maNVVPParameter, tenNVVPParameter, tenNhaThauParameter, hangMucParameter, nDViPhamParameter, ngayVPParameter, mucVPParameter, tongVPParameter, catTheParameter);
        }
    }
}
