//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int IDViPham { get; set; }
        public string MaNVVP { get; set; }
        public string TenNVVP { get; set; }
        public string TenNhaThau { get; set; }
        public string HangMuc { get; set; }
        public string NDViPham { get; set; }
        public Nullable<System.DateTime> NgayVP { get; set; }
        public string MucVP { get; set; }
        public Nullable<int> TongVP { get; set; }
        public Nullable<bool> CatThe { get; set; }
    }
}
